### ISSUE TITLE
Creating a topic if it doesn't yet exist

### ISSUE THREAD

**Issue by filipefigcorreia** [zendesk/ruby-kafka#62]
I believe that the `auto.create.topics.enable` setting of the Kafka server is not being honoured. By default the value of this setting is `true`, which means that when trying to produce to a non-existing topic, Kafka should create it instead of returning an error. 

Example:

    > kafka = Kafka.new(
    >         seed_brokers: [Settings.kafka.broker],
    >         client_id: Settings.kafka.client_id,
    >         logger: Logger.new($stderr),
    >     ) 
    > prod = kafka.get_producer
    > prod.produce('{"a":1}', topic: "testtopic")
    I, [2016-02-10T17:03:55.881822 #26727]  INFO -- : Trying to initialize broker pool from node localhost:9092
    I, [2016-02-10T17:03:55.882356 #26727]  INFO -- : Opening connection to localhost:9092 with client id sessions_api...
    D, [2016-02-10T17:03:55.888256 #26727] DEBUG -- : Sending request 1 to localhost:9092
    D, [2016-02-10T17:03:55.888625 #26727] DEBUG -- : Waiting for response 1 from localhost:9092
    D, [2016-02-10T17:03:55.898070 #26727] DEBUG -- : Received response 1 from localhost:9092
    I, [2016-02-10T17:03:55.898310 #26727]  INFO -- : Initialized broker pool with brokers: [192.168.1.98:9092 (node_id=0)]
    D, [2016-02-10T17:03:55.898408 #26727] DEBUG -- : Closing socket to localhost:9092
    Kafka::UnknownTopicOrPartition: unknown topic testtopic
      from /Users/fcorreia/.rvm/gems/ruby-2.3.0/gems/ruby-kafka-0.1.3/lib/kafka/protocol/metadata_response.rb:131:in `partitions_for'
      from /Users/fcorreia/.rvm/gems/ruby-2.3.0/gems/ruby-kafka-0.1.3/lib/kafka/broker_pool.rb:44:in `partitions_for'
      from /Users/fcorreia/.rvm/gems/ruby-2.3.0/gems/ruby-kafka-0.1.3/lib/kafka/producer.rb:158:in `produce'
      from (irb):54

**Comment by dasch** [comment]
I'll try to investigate this.

**Comment by mrkamel** [comment]
it seems, now you get a Kafka::LeaderNotAvailable exception when producing messages to a not yet existing topic. Only after creating a new kafka connection, the newly created topic will be recognized

```ruby
irb> producer.produce("message", :topic => "new_topic")
=> 0.6035724008894491
irb> producer.send_messages
Kafka::LeaderNotAvailable: Kafka::LeaderNotAvailable
....

> producer = Kafka.new(:seed_brokers => ["127.0.0.1:9092"], :client_id => "photobay", :logger => Logger.new("/dev/null"))
irb> producer.produce("message", :topic => "new_topic")
=> 0
irb> producer.send_messages
=> nil
```

desired behaviour?

**Comment by filipefigcorreia** [comment]
I got this behaviour too. It only went away after restarting zookeeper and kafka and publishing a message to the topic using the console producer.

**Comment by dasch** [comment]
Have you tried increasing the timeouts and retries? See the README for a decription of the various config keys.  It takes a while for Kafka to create the topic and elect a leader.

**Comment by mrkamel** [comment]
As far as i can see from a first sight into the respective code, the timeout and retry handling isn't in place for this case. ProduceOperation#execute invokes `@broker_pool.get_leader(topic, partition)` and no  leader is found, raising the exception. The exception handling is only used for actual responses to produce requests, not for the find leader operation. Please correct me if i'm wrong.

**Comment by dasch** [comment]
Hmm, that seems about right. I'll create a spec to replicate this bug and get it fixed.

**Comment by dasch** [comment]
Further complicating this issue is that if the topic doesn't exist at the time `#produce` is called. I'll merge #65 before fixing this, at that gives us a single retry loop and keeps `#produce` free of these concerns.

**Comment by dasch** [comment]
@filipefigcorreia @mrkamel can you try this out on the latest master?

**Comment by mrkamel** [comment]
it's still the same for me. Now it raises `Kafka::LeaderNotAvailable` within assign_partitions!
In addition, i'd like to mention, that now `ProduceOperation#execute` only catches LeaderNotAvailable. However, `BrokerPool#fetch_cluster_info`, which is called during `@broker_pool.get_leader(...)` in `ProduceOperation#execute`, could raise `ConnectionError` as well. I guess this should be catched as well.

**Comment by dasch** [comment]
I'll handle that as well.

**Comment by dasch** [comment]
@mrkamel have you tried increasing the timeouts or retries? I've got a passing functional test.

**Comment by dasch** [comment]
Ah, LeaderNotAvailable was not a subclass of Kafka::Error. Please try again.

**Comment by dasch** [comment]
Also: can you try increasing retries and backoff to at least 30s in total and include a full logging session?

**Comment by dasch** [comment]
I think I found the issue: `assign_partitions!` only rescued Kafka::Error, of which Kafka::LeaderNotAvailable was erroneously not a subclass. In my functional test I assigned a partition explicitly, so the code in question was not evaluated there.

**Comment by mrkamel** [comment]
still need more info?

**Comment by dasch** [comment]
I think it's fixed in the latest master – would be great if you could confirm.

**Comment by mrkamel** [comment]
working :+1:  thank you

**Comment by dasch** [comment]
Awesome!

**Comment by kyprifog** [comment]
I still get this behavior on 0.3.18.beta2.  Situation is that topic does not exist beforehand I get `Kafka::LeaderNotAvailable` error when trying to produce messages to the topic created by ruby-kafka.  Topics manually created on the broker do not yield the same behavior, have no issue with Leader and can produce.

**Comment by dasch** [comment]
@kyprifog are you using the async or the sync producer? If you're using the latter, you'll need to back off until a leader has been elected for each partition in the new topic. The async producer should do this automatically.

Topic creation isn't immediate, it can take a while, especially if you have lots of partitions.
