### ISSUE TITLE
SSL verification breaks Heroku Kafka

### ISSUE THREAD

**Issue by gaffneyc** [zendesk/ruby-kafka#734]
Heroku's hosted Kafka service uses certificates to handle client authentication but those certificates do not match the instance hostnames. This was working fine in previous versions of ruby-kafka but as of 741e6b80974b7f7979e8e2a8e59c57a57a7c4f4e all certificates must match their hostname and there is no way to disable this.

Ideally we have a way to disable certificate verification (or possibly just hostname verification).

* Version of Ruby:
2.6.3

* Version of Kafka:
[Heroku Multi-Tenant](https://devcenter.heroku.com/articles/kafka-on-heroku) Kafka 2.0.1 

* Version of ruby-kafka:
0.7.7

Please verify that the problem you're seeing hasn't been fixed by the current `master` of ruby-kafka.

###### Steps to reproduce

```ruby
@client = Kafka.new({
  client_id: client_id,
  seed_brokers: Figaro.env.kafka_url,
  ssl_ca_cert: Figaro.env.kafka_trusted_cert,
  ssl_client_cert: Figaro.env.kafka_client_cert,
  ssl_client_cert_key: Figaro.env.kafka_client_cert_key,
})
@consumer = @client.consumer(group_id: "#{Figaro.env.kafka_prefix}#{consumer_name}"))
@consumer.subscribe("#{Figaro.env.kafka_prefix}#{topic}"), start_from_beginning: false)

```

###### Expected outcome

As with ruby-kafka 0.7.6, I would expect we can connect to the Kafka cluster.

###### Actual outcome

What actually happened.
```
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unspecified certificate verification error)
```

**Comment by gaffneyc** [comment]
Just noticed #733 seems to be a fix for this exact issue

**Comment by dorner** [comment]
I'm having the same issue on my end btw.

**Comment by gaffneyc** [comment]
This should be fixed by c432f9e but still waiting on a release.

**Comment by dasch** [comment]
v0.7.8 should be out now.

**Comment by gaffneyc** [comment]
Thanks, I saw that and it's on my list to test today. Should know for sure in the next hour or so.

**Comment by gaffneyc** [comment]
Deployed and everything looks good. Thanks!

**Comment by wilsonsilva** [comment]
I'm still getting this error with `delivery_boy 0.2.8` (`ruby-kafka 0.7.10`):

```ruby
# config/initializers/delivery_boy.rb

DeliveryBoy.configure do |config|
  config.delivery_interval   = 1
  config.delivery_threshold  = 1
  config.ssl_verify_hostname = false
  config.ssl_client_cert     = ENV['KAFKA_CLIENT_CERT']
  config.ssl_client_cert_key = ENV['KAFKA_CLIENT_CERT_KEY']
  config.ssl_ca_cert         = ENV['KAFKA_TRUSTED_CERT']
  config.brokers             = ENV.fetch('KAFKA_URL').split(',')
end
```

```ruby
DeliveryBoy.deliver_async('hello', topic: 'supra-41634.test')
```

```
[Producer supra-41634.test] Unexpected Kafka error OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unspecified certificate verification error)
/app/vendor/bundle/ruby/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/ssl_socket_with_timeout.rb:69:in `connect_nonblock'
/app/vendor/bundle/ruby/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/ssl_socket_with_timeout.rb:69:in `initialize'
/app/vendor/bundle/ruby/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/connection.rb:127:in `new'
/app/vendor/bundle/ruby/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/connection.rb:127:in `open'
/app/vendor/bundle/ruby/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/connection.rb:98:in `block in send_request'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.0/lib/active_support/notifications.rb:182:in `instrument'
/app/vendor/bundle/ruby/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/instrumenter.rb:21:in `instrument'
/app/vendor/bundle/ruby/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/connection.rb:97:in `send_request'
/app/vendor/bundle/ruby/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/broker.rb:200:in `send_request'
/app/vendor/bundle/ruby/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/broker.rb:44:in `fetch_metadata'
/app/vendor/bundle/ruby/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/cluster.rb:375:in `block in fetch_cluster_info'
/app/vendor/bundle/ruby/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/cluster.rb:370:in `each'
/app/vendor/bundle/ruby/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/cluster.rb:370:in `fetch_cluster_info'
/app/vendor/bundle/ruby/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/cluster.rb:350:in `cluster_info'
/app/vendor/bundle/ruby/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/cluster.rb:98:in `refresh_metadata!'
/app/vendor/bundle/ruby/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/cluster.rb:102:in `refresh_metadata_if_necessary!'
/app/vendor/bundle/ruby/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/producer.rb:396:in `block in deliver_messages_with_retries'
/app/vendor/bundle/ruby/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/producer.rb:390:in `loop'
/app/vendor/bundle/ruby/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/producer.rb:390:in `deliver_messages_with_retries'
/app/vendor/bundle/ruby/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/producer.rb:253:in `block in deliver_messages'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.0/lib/active_support/notifications.rb:182:in `instrument'
/app/vendor/bundle/ruby/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/instrumenter.rb:21:in `instrument'
/app/vendor/bundle/ruby/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/producer.rb:246:in `deliver_messages'
/app/vendor/bundle/ruby/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/async_producer.rb:266:in `deliver_messages'
/app/vendor/bundle/ruby/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/async_producer.rb:211:in `block in run'
/app/vendor/bundle/ruby/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/async_producer.rb:203:in `loop'
/app/vendor/bundle/ruby/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/async_producer.rb:203:in `run'
/app/vendor/bundle/ruby/2.6.0/gems/ruby-kafka-0.7.10/lib/kafka/async_producer.rb:154:in `block (2 levels) in ensure_threads_running!'
[Producer supra-41634.test] Async producer crashed!
```

**Comment by alan-sapaad** [comment]
@wilsonsilva Can you try setting `config.ssl_verify_hostname =  false`

**Comment by wilsonsilva** [comment]
I had that configuration already. I solved this eventually.

The problem was not Delivery boy but Karafka.

**Comment by psk86** [comment]
@wilsonsilva What was the problem ? How did you resolve the `unspecified certificate verification error` issue ?

**Comment by wilsonsilva** [comment]
I had to change the Karafka configurations from `config.setting` to `config.kafka.setting`.
